name: turborepo-boilerplate
services:
  app:
    build:
      context: .
      secrets:
        - env
    env_file:
      - .env
    ports:
      - "3330:3330"
      - "8000:8000"
    container_name: turborepo-boilerplate

secrets:
  env:
    file: .env
